# Generated by Django 5.0.3 on 2024-03-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField(blank=True, null=True)),
                ('cus_id', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('u_price', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
    ]
